version: '3.7'
services:
  app:
    image: node:15.14.0-alpine
    container_name: nextjs-sample-app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    entrypoint: /bin/sh -c "yarn && apk add bash && bash"
